# Generated by Django 4.2.2 on 2023-11-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=120, unique=True)),
                ('Nombre', models.CharField(max_length=120)),
                ('Descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('InformacionAdicional', models.TextField(blank=True, null=True)),
                ('Cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('UnidadMedida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('PrecioCosto', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('CostoDolar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Stock', models.IntegerField(blank=True, default=0, null=True)),
                ('HabilitarVenta', models.BooleanField(default=False)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.categoria')),
                ('Proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.proveedor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='movimientoInventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('InformacionAdicional', models.TextField(blank=True, null=True)),
                ('Estado', models.BooleanField(default=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('DepositoEntrada', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_entrada', to='configuracion.deposito')),
                ('DepositoSalida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_salida', to='configuracion.deposito')),
                ('Producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'Movimientos deposito',
            },
        ),
    ]
