# Generated by Django 4.2.7 on 2023-12-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_compra_producto_precio_final_venta_detalleventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='codigo',
        ),
    ]
