# Generated by Django 4.2.2 on 2023-11-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('FechaOrden', models.DateTimeField(auto_now_add=True, null=True)),
                ('FechaEntrega', models.DateField(blank=True, null=True)),
                ('Comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('TotalOrden', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.cliente')),
            ],
            options={
                'verbose_name': 'sesion',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Nombre', max_length=150, unique=True)),
                ('Rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Comentarios', models.TextField(blank=True, null=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('GeneraComanda', models.BooleanField(default=False)),
                ('Estado', models.BooleanField(default=False)),
                ('Categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuracion.categoria')),
            ],
            options={
                'verbose_name': 'tratamiento',
                'verbose_name_plural': 'Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='subReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, unique=True)),
                ('Detalles', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('Porciones', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'tratamiento base',
                'verbose_name_plural': 'Tratamiento base',
            },
        ),
        migrations.CreateModel(
            name='subRecetaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.receta')),
                ('SubReceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.subreceta')),
            ],
            options={
                'verbose_name': 'sub tratamiento',
                'verbose_name_plural': 'Sub tratamiento incluido en el tratamiento',
            },
        ),
        migrations.CreateModel(
            name='productoSubReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('MedidaUso', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=20)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('SubReceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.subreceta')),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'Insumos incluidos en el sub-tratamiento',
            },
        ),
        migrations.CreateModel(
            name='productoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('MedidaUso', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.receta')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'Productos incluidos en tratamiento',
            },
        ),
        migrations.CreateModel(
            name='productoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('MedidaUso', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=20)),
                ('CostoUnitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.orden')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.receta')),
            ],
        ),
        migrations.CreateModel(
            name='gastosAdicionalesReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('Adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.gastosadicionales')),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.receta')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'Adicionales incluidos en la tratamiento',
            },
        ),
    ]
