# Generated by Django 4.2.7 on 2023-12-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrecetareceta',
            name='Receta',
        ),
        migrations.RemoveField(
            model_name='subrecetareceta',
            name='SubReceta',
        ),
        migrations.AddField(
            model_name='orden',
            name='costoFinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='receta',
            name='costo_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.DeleteModel(
            name='productoSubReceta',
        ),
        migrations.DeleteModel(
            name='subReceta',
        ),
        migrations.DeleteModel(
            name='subRecetaReceta',
        ),
    ]
