# Generated by Django 4.2.7 on 2024-01-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0003_orden_detalle_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasCara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='receta',
            name='Nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_de_consulta', models.TextField(blank=True, null=True)),
                ('biotipo_cutaneo', models.CharField(blank=True, choices=[('Piel eudérmica', 'Piel eudérmica'), ('Piel seborreica', 'Piel seborreica'), ('Piel alipídica', 'Piel alipídica'), ('Piel sensible', 'Piel sensible'), ('Piel sensibilizada', 'Piel sensibilizada')], max_length=255, null=True)),
                ('biotipo_estado', models.CharField(blank=True, choices=[('Hidratado', 'Hidratado'), ('Deshidratado', 'Deshidratado'), ('Asfíctico', 'Asfíctico')], max_length=255, null=True)),
                ('fototipo_cutaneo', models.PositiveIntegerField(blank=True, null=True)),
                ('acromica', models.ManyToManyField(blank=True, related_name='acromica', to='cocina.areascara')),
                ('cicatrices', models.ManyToManyField(blank=True, related_name='cicatrices', to='cocina.areascara')),
                ('comedon_abierto', models.ManyToManyField(blank=True, related_name='comedon_abierto', to='cocina.areascara')),
                ('comedon_cerrado', models.ManyToManyField(blank=True, related_name='comedon_cerrado', to='cocina.areascara')),
                ('eritema', models.ManyToManyField(blank=True, related_name='eritema', to='cocina.areascara')),
                ('hematoma', models.ManyToManyField(blank=True, related_name='hematoma', to='cocina.areascara')),
                ('hiperpicmentada', models.ManyToManyField(blank=True, related_name='hiperpicmentada', to='cocina.areascara')),
                ('hipopicmentaria', models.ManyToManyField(blank=True, related_name='hipopicmentaria', to='cocina.areascara')),
                ('macula_picmentaria', models.ManyToManyField(blank=True, related_name='macula_picmentaria', to='cocina.areascara')),
                ('macula_vascular', models.ManyToManyField(blank=True, related_name='macula_vascular', to='cocina.areascara')),
                ('nodulo', models.ManyToManyField(blank=True, related_name='nodulo', to='cocina.areascara')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.orden')),
                ('papula', models.ManyToManyField(blank=True, related_name='papula', to='cocina.areascara')),
                ('petequias', models.ManyToManyField(blank=True, related_name='petequias', to='cocina.areascara')),
                ('placa', models.ManyToManyField(blank=True, related_name='placa', to='cocina.areascara')),
                ('purpura', models.ManyToManyField(blank=True, related_name='purpura', to='cocina.areascara')),
                ('pustula', models.ManyToManyField(blank=True, related_name='pustula', to='cocina.areascara')),
                ('quiste_de_millium', models.ManyToManyField(blank=True, related_name='quiste_de_millium', to='cocina.areascara')),
                ('telangiectasias', models.ManyToManyField(blank=True, related_name='telangiectasias', to='cocina.areascara')),
                ('tuberculo', models.ManyToManyField(blank=True, related_name='tuberculo', to='cocina.areascara')),
            ],
        ),
    ]
