# Generated by Django 4.2.7 on 2024-05-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0004_areascara_alter_receta_nombre_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='diagnostico_final',
            field=models.TextField(default='No terminado'),
        ),
    ]
