# Generated by Django 4.2.2 on 2023-11-08 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=120, unique=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('NumeroCliente', models.AutoField(primary_key=True, serialize=False)),
                ('NombreApellido', models.CharField(max_length=120)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=120, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'deposito',
                'verbose_name_plural': 'Deposito',
            },
        ),
        migrations.CreateModel(
            name='gastosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos adicionales',
            },
        ),
        migrations.CreateModel(
            name='medioDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'medio de compra',
                'verbose_name_plural': 'Medios de compra',
            },
        ),
        migrations.CreateModel(
            name='medioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'medio de pago',
                'verbose_name_plural': 'Medios de pago',
            },
        ),
        migrations.CreateModel(
            name='miEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=100, unique=True)),
                ('Moneda', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('COL', 'COL'), ('BOL', 'BOL')], default='ARS', max_length=20)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('Horarios', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'Mi empresa',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=120)),
                ('NombreApellido', models.CharField(max_length=120)),
                ('Direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Telefono', models.CharField(max_length=120)),
                ('UltimaModificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'Roles de usuario',
            },
        ),
        migrations.CreateModel(
            name='usuarioCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.deposito')),
                ('Rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.rol')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignacion',
                'verbose_name_plural': 'Asignacion Deposito',
            },
        ),
    ]
