# Generated by Django 4.2.7 on 2025-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('facial', 'Facial'), ('corporal', 'Corporal')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('beneficio_uno', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficio_dos', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficio_tres', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(upload_to='servicios/')),
                ('duracion', models.CharField(help_text='Ej: 60 minutos', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
